name: Publish NodeJS project to Github Pages

on:
    push:
        branches: [master]

jobs:
    build-push-to-github-pages:
        runs-on: ubuntu-latest

        steps:
        - name: Use Node
          uses: actions/setup-node@v6
          with:
            node-version: '22.19.0'
        - name: Install dependencies
          run: npm install
        - name: Build Node Project
          run: npm run build
        - name: Copy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: ./dist